
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-zindogch-com-tls
  namespace: argocd
spec:
  secretName: argocd-zindogch-com-tls
  duration: 2160h0m0s #90day
  renewBefore: 360h0m0s #before 15day
  issuerRef:
    name: my-issuer
    kind: ClusterIssuer
  commonName: argocd.zindogch.com
  dnsNames:
  - argocd.zindogch.com
